[workspace]
resolver = "2"
members = [
	"youmubot-prelude",
	"youmubot-db",
	"youmubot-db-sql",
	"youmubot-core",
	"youmubot-cf",
	"youmubot-osu",
	"youmubot",
]
[workspace.lints.rust]
deprecated = "allow"
