use serde::Deserialize;

#[derive(Deserialize, Debug)]
pub(crate) struct Beatmap {
    pub approved: String,
    pub submit_date: String,
    pub approved_date: Option<String>,
    pub last_update: String,
    pub artist: String,
    pub beatmap_id: String,
    pub beatmapset_id: String,
    pub bpm: String,
    pub creator: String,
    pub creator_id: String,
    pub difficultyrating: String,
    pub diff_aim: Option<String>,
    pub diff_speed: Option<String>,
    pub diff_size: String,
    pub diff_overall: String,
    pub diff_approach: String,
    pub diff_drain: String,
    pub hit_length: String,
    pub source: Option<String>,
    pub genre_id: String,
    pub language_id: String,
    pub title: String,
    pub total_length: String,
    pub version: String,
    pub file_md5: String,
    pub mode: String,
    pub tags: String,
    pub favourite_count: String,
    pub rating: String,
    pub playcount: String,
    pub passcount: String,
    pub count_normal: String,
    pub count_slider: String,
    pub count_spinner: String,
    pub max_combo: Option<String>,
    pub download_unavailable: String,
    pub audio_unavailable: String,
}
